name: Close Pull Request

on:
  pull_request_target:
    types: [opened]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: superbrothers/close-pull-request@v3
      with:
        comment: "Hello! \n\nWe appreciate your contribution but only Pull Requests made in the source repository will be considered. \n\n(https://codeberg.org/Zettexe/Cirvano)"
